# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
# Site settings
title: "YoungbinLab Blog"
description: "Logs of Youngbin han's Laboratory"
email: sukso96100@gmail.com

name: 'Youngbin Han'
author: 'Youngbin Han'

paginate: 10

url: "http://sukso96100.github.io/" # the base hostname & protocol for your site
baseurl: "/blog"